return {
  { 'rebelot/kanagawa.nvim', as = 'kanagawa' },
  { 'rose-pine/neovim', as = 'rose-pine' },
  { 'catppuccin/nvim', as = 'catppuccin' },
  -- { 'ellisonleao/gruvbox.nvim', as = 'gruvbox' },
  -- { 'franbach/miramare', as = 'miramare' },
  { 'edeneast/nightfox.nvim', as = 'nightfox.nvim' },
  { 'sainnhe/gruvbox-material', as = 'gruvbox-material' },
  -- { 'sainnhe/sonokai', as = 'sonokai' },
  { 'folke/tokyonight.nvim', as = 'tokyonight' },
  { 'neanias/everforest-nvim', as = 'everforest' },
  -- { 'diegoulloao/neofusion.nvim', as = 'neofusion' },
  -- { '0xstepit/flow.nvim', as = 'flow' },
  -- commented that one out because it's the same as neofusion
  -- { '2giosangmitom/nightfall.nvim', as = 'nightfall' },
  { 'navarasu/onedark.nvim', as = 'onedark' },
  -- { 'scottmckendry/cyberdream.nvim', as = 'cyberdream' },
  { 'tiagovla/tokyodark.nvim', as = 'tokyodark' },
  -- { 'sainnhe/edge', as = 'edge' },
}
